spring.application.name=msvc-eureka
# Puerto estandar del servidor Eureka. El panel queda en http://localhost:8761
server.port=8761

# El propio servidor NO se registra ni descarga el registro: el es el registro.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
